apiVersion: v1
kind: Service
metadata:
  name: cowrie-service
  namespace: honeypots
spec:
  selector:
    app: cowrie
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: ssh-port
