apiVersion: apps/v1
kind: Deployment
metadata:
  name: dionaea
  namespace: honeypots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dionaea
  template:
    metadata:
      labels:
        app: dionaea
    spec:
      containers:
        - name: dionaea
          image: dinotools/dionaea:latest
          ports:
            - containerPort: 21  # FTP
            - containerPort: 445 # SMB
            - containerPort: 135 # RPC
          volumeMounts:
            - name: dionaea-logs
              mountPath: /opt/dionaea/var/log
        - name: promtail
          image: grafana/promtail:2.9.2
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: dionaea-logs
              mountPath: /var/log/dionaea
            - name: promtail-config
              mountPath: /etc/promtail
              readOnly: true
      volumes:
        - name: dionaea-logs
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: promtail-dionaea-config
