apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-dionaea-config
  namespace: honeypots
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
      - job_name: dionaea
        static_configs:
          - targets:
              - localhost
            labels:
              job: dionaea
              app: dionaea
              __path__: /var/log/dionaea/*.log
