apiVersion: v1
kind: Service
metadata:
  name: dionaea-service
  namespace: honeypots
spec:
  selector:
    app: dionaea
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      name: ftp
    - protocol: TCP
      port: 445
      targetPort: 445
      name: smb
    - protocol: TCP
      port: 135
      targetPort: 135
      name: rpc
